### PR TITLE
Explore

### PR DESCRIPTION
**Pull request by harshitpaliwal95**
### update explore page
- add Chips
- added filter by category

https://user-images.githubusercontent.com/60725346/161429568-668c506e-babc-465b-aaf4-6795bd945294.mov

### CODE REVIEW

**Review by rahul31agrawal — APPROVED** [review]
Hi Harshit,
1. Yor App works amazingly smooth
2. Your UI looks awesome
3. The Code structure is clean
Looks good to merge
Thanks

**Review by Balakumar3018 — APPROVED** [review]
Everything looks great. Good to merge.

**Comment by pruthvirajmv** [comment]
Hey Harshit,
Please go through the comments and resolve 
Apart from that project looks good
Happy & keep coding!

**Comment by harshitpaliwal95** [comment]
> 

thanks @pruthvirajmv for Pr review and feedback I almost resolve everything now the code looks really clean and optimize

**Pull request merged**
